services:
  jekyll-site:
    image: jekyll-site
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "4000:4000"     # Jekyll サーバー用
      - "35729:35729"   # LiveReload 用
    user: "1000:1000"
    environment:
      - JEKYLL_ENV=docker
    # command: jekyll serve -H 0.0.0.0 --watch --force_polling --livereload --config _config.yml,_config_docker.yml
